Update .gitmodules after channel switch

diff --git a/flutterw b/flutterw
--- a/flutterw
+++ b/flutterw
@@ -76,3 +76,26 @@ fi
 # Wrapper tasks done, call flutter binay with all args
 set -e
 "$FLUTTER_DIR/bin/flutter" "$@"
+
+# Post flutterw tasks. exit code from /bin/flutterw will be used as final exit
+FLUTTER_EXIT_STATUS=$?
+if [ $FLUTTER_EXIT_STATUS -eq 0 ]; then
+
+  # ./flutterw channel CHANNEL
+  if echo $@ | grep -q "channel"; then
+    # make sure .gitmodules is updated as well
+    CHANNEL=${2} # second arg
+    git config -f .gitmodules submodule.$FLUTTER_SUBMODULE_NAME.branch $CHANNEL
+    git add .gitmodules
+  fi
+
+  # ./flutterw upgrade
+  if echo $@ | grep -q "upgrade"; then
+    # statge submodule changes, makes sure nobody forgets to do it
+    git add $FLUTTER_SUBMODULE_NAME
+    # flutter packages get runs automatically. Stage those changes as well
+    git add pubspec.lock
+  fi
+
+fi
+exit $FLUTTER_EXIT_STATUS
